### ISSUE TITLE
Cadastro de oficinas

### ISSUE THREAD

**Issue by ViniciusOgawa** [Oficina-de-Integracao-2/front-end#2]
Campos do Formulário:

Nome da Oficina (Obrigatório)
Descrição da Oficina (Obrigatório)
Data e Hora (Obrigatório)
Localização ou Plataforma (Online) (Obrigatório)
Nome do Instrutor (Obrigatório)
E-mail de Contato do Instrutor (Opcional)
Capacidade Máxima de Participantes (Obrigatório)

**Comment by Willian-zentil** [comment]
[commit cadastro de oficinas
](https://github.com/Oficina-de-Integracao-2/front-end/commit/11d398a1e48404e3a0f0a78bdeced6450019cf6f)
